# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
   - postgres:latest

before_script:
  - sudo apt-get -y install npm
  - sudo apt-get -y install nodejs
  - cd backend
  - npm install
  - npm install mocha

test_server:
  script:
    - alias node=nodejs
    - npm test
