 # https://hub.docker.com/r/library/node/tags/
 image: node:latest

 # Pick zero or more services to be used on all builds.
 # Only needed when using a docker container to run your tests in.
 # Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
 services:
   - postgres:latest

before_script:
  - npm install

test_server:
  script:
    - npm install
    - npm install mocha
    - node index.js 
